#!/usr/bin/env bash
# This script pings an IP address passed as an argument

args="$#"
if ((args == 0));
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif ((args > 0));
then
    ping -c 5 "$1"
fi