#!/usr/bin/env bash
# This script displays the iteration on normal iteration
# displays bad luck from China on the 4 iteration
# displays bad luck from Japan on the 9 iteration
# displays bad luck from Italy on the 17 iteration

a=1
while [ $a -lt 21 ];
do
    echo $a
    case $a in
    4)
        echo 'bad luck from China'
        ;;
    9)
        echo 'bad luck from Japan'
        ;;
    17)
        echo 'bad luck from Italy'
        ;;
    esac
    a=$((a+1))
done