#!/usr/bin/env bash
# This script configure an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.old
sed -i 's/127.*$/127.0.0.2  localhost\n8.8.8.8  facebook.com/' /etc/hosts.old
cp -f /etc/hosts.old /etc/hosts